apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: vault-seal-unseal-hooks
  namespace: kasten-io
actions:
  backupPrehook:
    phases:
      - func: KubeTask
        name: unseal
        args:
          namespace: vault
          image: quay.io/openshift/origin-cli:latest
          podOverride:
            spec:
              serviceAccountName: vault-kanister
          command:
            - /bin/sh
            - -c
            - |
              VAULT_POD=$(oc get pods -n vault -l app.kubernetes.io/name=vault -o jsonpath='{.items[0].metadata.name}')
              VAULT_UNSEAL_KEY=$(oc get secret vault-unseal-key -n vault -o jsonpath='{.data.unseal_key}' | base64 --decode)
              echo "Unsealing Vault pod: $VAULT_POD"
              oc exec -n vault $VAULT_POD -- vault operator unseal $VAULT_UNSEAL_KEY
  backupPosthook:
    phases:
      - func: KubeTask
        name: seal
        args:
          namespace: vault
          image: quay.io/openshift/origin-cli:latest
          podOverride:
            spec:
              serviceAccountName: vault-kanister
          command:
            - /bin/sh
            - -c
            - |
              VAULT_POD=$(oc get pods -n vault -l app.kubernetes.io/name=vault -o jsonpath='{.items[0].metadata.name}')
              VAULT_TOKEN=$(oc get secret vault-unseal-key -n vault -o jsonpath='{.data.root_token}' | base64 --decode)
              echo "Sealing Vault pod: $VAULT_POD"
              oc exec -n vault $VAULT_POD -- env VAULT_TOKEN=$VAULT_TOKEN vault operator seal
